model = "gpt-5.4"
model_reasoning_effort = "medium"
model_provider = "isomoes"

[model_providers.isomoes]
name = "isomoes api"
base_url = "https://aiapi.isomoes.site/v1"
env_key = "AIAPI_AUTH_KEY"

[projects."/home/isomoes"]
trust_level = "trusted"
